export const ERROR_MESSAGE = {
  DEFAULT: 'Something went wrong',
  SESSION_EXPIRED: 'Session expired. Redirecting to login...',
  FILE_SIZE_LIMIT: 'File size must lesser that 50MB!',
  IMAGE_SIZE_LIMIT: 'File size must lesser that 5MB!',
  IMAGE_SIZE_LESS: 'Image size must be greater that 100KB!',
  FILE_NAME_INVALID: 'File name must be unique!',
  FILE_CONTENT_DUPLICATE: 'File name and content must be unique',
  INVALID_FILE: 'Invalid file type!',
  UPLOAD_FAILED: 'Failed to upload fail',
  NO_OF_FILES: (limit: number, fileType: string) => `Can't upload more than ${limit} ${fileType}!`,
  EDITOR_ERROR: 'Error updating editor',
  DRAG_FILE_FAIL: 'Failed to drag file',
  BUY_TOKEN_FAILED: 'Failed to buy token',
  FAILED_TO_READ_FILE: 'Failed to read file',
  PASSWORD_ENCRYPTED_FILE: 'Password encrypted file was not allowed',
  FAILED_TO_DELETE_ASSET: 'Failed to delete asset',
  FAILED_TO_MARK_AS_READ: 'Failed to mark as read',
  VIEW_NOTIFICATION: 'Failed to view notification',
  IMAGE_REJECTED: 'Uploaded image rejected, Please Upload clear images',
  FAILED_TO_UPLOAD_IMAGE: 'Failed to upload Image',
  LIST_TOKEN_FAILED: 'Failed to list token',
  DELETE_LISTINGS: 'Failed to delete listings',
  WALLET_NOT_CONNECTED: 'Connect your wallet',
  LISTING_NOT_FOUND: 'LISTING NOT FOUND',
  INSUFFICIENT_USDC_BALANCE: 'Insufficient USDC balance to complete the purchase.',
  INSUFFICIENT_POL_BALANCE: 'Insufficient POL balance,Fund your wallet with POL.',
  USER_DENIED_FAILED: 'Transaction Denied',
  LOGIN_REQUIRED: 'Login to proceed.',
  WALLET_ALREADY_USED: 'This wallet has already been used. Please connect a different account.',
  PROFILE_TYPE: 'Please upload only image files (JPEG, PNG, GIF, WEBP)',
  KYC_VERIFICATION: 'Complete KYC verification to Proceed Further',
  KYC_PENDING: 'Your KYC is Pending , please come back later',
};
