export const SUCCESS_MESSAGES = {
  ASSET_CREATED: 'Asset created successfully',
  ASSET_UPDATED: 'Asset updated successfully',
  ASSET_APPROVED: 'Asset approved successfully',
  ASSET_LIST: 'Asset listed successfully',
  ASSET_REJECTED: 'Asset rejected successfully',
  ASSET_HOLD: 'Asset kept on hold successfully',
  ASSET_DELISTED: 'Asset delisted successfully',
  ASSET_DELETED: 'Asset deleted successfully',
  ASSET_EDITED: 'Asset edited successfully',
  TOKENS_ISSUED: 'Tokens issued successfully',
  DOCUMENT_APPROVED: 'Document approved successfully',
  DOCUMENT_REJECTED: 'Document rejected successfully',
  DOCUMENT_APPROVAL_REMOVED: 'Document approval removed successfully',
  USER_ACTIVATED: 'User activated successfully',
  USER_TERMINATED: 'User terminated successfully',
  USER_SUSPENDED: 'User suspended successfully',
  ASSET_DRAFTED: 'Your changes saved successfully',
  MARKED_AS_READ: 'Notifications marked as read successfully',
  NOTIFICATION_VIEWED: 'Notification viewed successfully',
  TOKEN_LISTED: 'Tokens listed successfully',
  DRAFT_DELETED: 'Draft deleted successfully',
  LISTING_DELETED: 'Listing deleted successfully',
  TOKEN_PURCHASED: 'Token purchased successfully',
  STRIPE_ACCOUNT_CONNECTED: 'Stripe account connected',
  APPROVAL_MESSAGE: 'Approved Successfully',
};
