import { ToSData } from '@/app/terms/interface';

export const termsData: ToSData = {
  buyer: {
    label: 'Buyer/Investor',
    heading: `Welcome to <b>Rareagora</b>, a marketplace that enables fractional ownership of real-world assets
through tokenization. By using our platform, you agree to the following terms and conditions
governing your participation as a buyer or investor.`,
    sections: [
      {
        title: 'DEFINITIONS',
        listItems: [
          `<b>"Rareagora"</b> refers to <b>Rareagora.com</b>, the online marketplace facilitating asset tokenization.`,
          `<b>"Buyer/Investor"</b> refers to any user purchasing asset tokens.`,
          `<b>"Asset Tokens"</b> represent fractional ownership in real-world assets available on the platform.`,
          `<b>"Seller refers"</b> to the asset owner listing an asset for fractionalization.`,
          `<b>"Smart Contract"</b> refers to blockchain-based agreements governing the tokenization and transactions.`,
        ],
      },
      {
        title: 'ELIGIBILITY',
        nested: [
          {
            heading: 'General Requirements',
            content: 'To participate as an investor:',
            listItems: [
              `You must comply with <b>KYC (Know Your Customer) and AML (Anti-Money Laundering) procedures</b> before making any investments.`,
              `The KYC would be of any of government ID credentials.`,
              `Your participation must comply with <b>local laws and regulations</b> regarding securities and asset investments.`,
            ],
          },
          {
            heading: 'Accredited Investor Status (If Required)',
            content: `Some asset investments may be <b>limited to accredited investors,</b> depending on regulatory
          requirements. You may need to verify your <b>income/net</b> worth to access specific investment
          opportunities.`,
          },
        ],
      },
      {
        title: 'ASSET TOKENIZATION & OWNERSHIP',
        nested: [
          {
            heading: 'Nature of Asset Tokens',
            listItems: [
              `All Asset tokens are created pegged to actual physical asset that exists which are
            verified with various authenticating parameters corresponding to the asset, authorized by
            experts.`,
              `Asset Tokens do not grant physical ownership of the underlying asset but represent
            fractional ownership rights.`,
              `Token holders may receive profit distributions (depending on assets), appreciation
            benefits, or participation in governance (if applicable) and also resale their tokens in
            marketplace.`,
            ],
          },
          {
            heading: 'Asset Appreciation',
            listItems: [
              `Asset tokens value are subject to change based on attributes such as rarity of asset,
          demand and many other influencing factors.`,
              `Investing in asset tokens carries market risks. The platform does not guarantee returns,
          liquidity, or appreciation of tokenized assets.`,
            ],
          },
        ],
      },
      {
        title: 'PAYMENT & TRANSACTION TERMS',
        nested: [
          {
            heading: 'Accepted Payment Methods',
            content: 'Buyers/Investors can purchase asset tokens using:',
            listItems: [
              `Fiat currencies (via bank transfers or credit/debit cards).`,
              `Cryptocurrencies (BTC, ETH, USDT, etc.), subject to platform policies.`,
            ],
          },
          {
            heading: 'Transaction Fees',
            listItems: [
              `A 3 - 5% transaction fee applies to all purchases.`,
              `Withdrawal of funds may incur additional processing fees based on payment method.`,
            ],
          },
          {
            heading: 'Refund & Cancellation Policy',
            listItems: [
              `All token purchases are final and non-refundable.`,
              `The platform is not responsible for market losses or price fluctuations`,
            ],
          },
        ],
      },
      {
        title: 'RETURN ON INVESTMENT (ROI)',
        listItems: [
          `<b>Income Generation:</b> Tokens may entitle holders to a share of income generated by the
          asset (e.g., rental income, dividends).`,
          `<b>Appreciation:</b> Token value may increase if the underlying asset appreciates over time
          with attributes such as rarity of asset, demand of asset and many other factors.`,
          `<b>No Guaranteed Returns:</b> Clearly state that investments are subject to market risks, and
          ROI is not guaranteed.`,
        ],
      },
      {
        title: 'NO SECONDARY MARKET TRADING',
        nested: [
          {
            heading: 'Trading on the Platform',
            listItems: [
              `Investors can trade asset tokens on the rareagora.com only.`,
              `Trading in secondary markets will be in near future.`,
            ],
          },
        ],
      },
      {
        title: 'RISKS & DISCLAIMERS',
        nested: [
          {
            heading: 'Market Risks',
            listItems: [
              `Asset prices fluctuate based on market demand and external factors.`,
              `Liquidity of fractionalized assets is not guaranteed at all times due to factors influencing
            the assets.`,
            ],
          },
          {
            heading: 'Regulatory & Legal Risks',
            listItems: [
              `Asset tokens may be subject to regulatory changes in different jurisdictions.`,
              `The platform does not provide legal or financial advice—users should consult their own
            advisors.`,
              `Changes in laws or regulations could impact the value or legality of tokenized assets.`,
              `The platform does not provide financial, legal, or tax advice. Users should consult
              professionals before investing.`,
            ],
          },
          {
            heading: 'Platform Security & Technical Risks',
            listItems: [
              `The platform uses blockchain technology for security, but risks like smart contract bugs,
              cyber-attacks, or network failures exist.`,
              `Users are responsible for the security of their wallets and private keys.`,
            ],
          },
        ],
      },
      {
        title: 'TAX & COMPLIANCE',
        listItems: [
          `Investors are responsible for declaring and paying any applicable taxes on their
          investment gains on their own.`,
          `The platform does not provide tax reporting tools, but investors must consult tax
          professionals for compliance.`,
        ],
      },
      {
        title: 'USER CONDUCT & RESTRICTIONS',
        nested: [
          {
            heading: 'Prohibited Activities',
            content: 'Users agree NOT to:',
            listItems: [
              `Engage in fraudulent or illegal activities, including money laundering.`,
              `Use the platform for manipulative trading or market abuse.`,
              `Attempt to exploit smart contract vulnerabilities.`,
              `Users can be suspended and terminated if found guilty of consistent flaws in asset submission process or breaching the agreement.`,
            ],
          },
        ],
      },
      {
        title: 'DISPUTE RESOLUTION',
        nested: [
          {
            heading: 'Governing Law',
            content: `These Terms shall be governed by and construed in accordance with legal frameworks
          specific to concerns raised by user from corresponding country. Please contact
          support@rareagora.com`,
          },
        ],
      },
      {
        title: 'MODIFICATIONS & TERMINATION',
        nested: [
          {
            heading: 'Changes to Terms',
            content: `The platform may update these Terms & Conditions at any time, with prior notice where applicable.`,
          },
          {
            heading: 'Account Termination',
            content: `The platform may suspend or terminate accounts found in violation of the terms.`,
          },
        ],
      },
      {
        title: 'CONTACT INFORMATION',
        content: `Email: <a href = "mailto:support@rareagora.com">support@rareagora.com</a>`,
      },
    ],
  },
  seller: {
    label: 'Seller',
    heading: `Welcome to Rare Agora’s Seller Terms and Conditions, governing your use of Rare Agora as your designated online marketplace to sell your assets through tokenization.
    By registering as a seller on Rare Agora, you agree to comply with these terms, which outline your rights, responsibilities, and obligations as a valued member of the Rare Agora network.
    These terms are designed to ensure a seamless, transparent, and mutually beneficial relationship between Rare Agora and our sellers. Please read this document carefully, as it contains important information regarding fees, product listings, customer interactions, and compliance with applicable laws and marketplace policies. Your continued use of Rare Agora as a seller constitutes your acceptance of these terms and any updates or modifications made to them.`,
    sections: [
      {
        title: 'Section 1: Register as a Seller',
        content: 'To use the services of Rare Agora and sell on our marketplace, you must register as a seller.',
        listItems: [
          'Create a seller account by completing the registration process. ',
          'Local laws and regulations may impose additional criteria to determine your eligibility as a seller. Submitting false or fraudulent identification will not be accepted and may result in further action by local authorities. ',
          '<b>Payment Providers</b>: To ensure a safe and trusted selling environment, we will collect payments on your behalf and transfer the proportionate amount to you after deducting our agreed charges within 24 hours of receiving the payment. ',
          'We may request additional information for compliance purposes. If you fail to provide this information, you will not be able to sell on Rare Agora. ',
          'Incomplete account registrations will be put on hold, and the seller will not be able to access any services until the registration is completed. ',
          'Registering as a seller automatically confirms your acceptance of all our terms and conditions.',
        ],
      },
      {
        title: 'Section 2: Product Submission',
        listItems: [
          'The seller must submit the product they intend to tokenize and sell on our marketplace, along with high-quality images and relevant documents.',
          'The details of the product’s country of origin must be provided, including whether the product is still in its country of origin. If not, the seller must specify when the product left its country of origin and its current location. ',
          'Clear, high-quality images and videos of the product must be submitted to accurately represent its current condition, features, and other particulars. This includes any stains, marks, damages, defects, deficiencies, or financial and legal obligations associated with the product. ',
          'The reserve price of the product must be mentioned during product submission. ',
          'Upon successful submission, our experts will verify, authenticate, and appraise the product. ',
          'After successful verification, the seller will be notified, and the product will be ready for asset tokenization. ',
          'If the verification, authentication, or appraisal of the product does not meet our experts’ requirements, the product will be rejected. ',
          'If additional information or clarification is required, the product will neither be approved nor rejected but placed on hold until the seller provides the required information. ',
          'Rare Agora reserves the right to accept, reject, or hold any product without notifying the seller or any other person or entity. ',
          'Continuously resubmitting false or rejected products is not allowed and may result in account suspension or termination. ',
          'The seller is solely responsible for providing accurate information, documents, and other relevant details of the product. Rare Agora is not responsible for any false or fraudulent information submitted by the seller. ',
          'The seller guarantees that they are authorized to tokenize their product.',
        ],
        contentMiddle: 'By authorizing their product for tokenization, the seller confirms that they will not: ',
        listItems2: [
          'Fail to comply with any legal or regulatory requirements, including those governing economic sanctions',
          'Infringe upon the rights of third parties, including contractual obligations and intellectual property protections. ',
          'Engage in illegal or deceitful behavior toward third parties or Rare Agora. ',
          'Present the product as part of a sham transaction to facilitate money laundering. ',
        ],
        contentEnd:
          'The seller guarantees that the product will be part of a <b>genuine and authentic</b> transaction.',
      },
      {
        title: 'Section 3: Asset Tokenization',
        listItems: [
          'Once the product is approved by our experts, it will be fractionalized into multiple asset tokens and made available in the marketplace for buyers and investors. ',
          'A separate contract will be signed for the asset tokenization process.',
        ],
      },
      {
        title: 'Section 4: Storage and Security',
        listItems: [
          'Before the tokenization process is executed and after acceptance by our expert team, the <b>real-world asset (RWA)</b> must be placed in the joint custody of <b>Amstar Metals (Parent company of Rare Agora) – Rare Agora</b> and the seller. ',
          'Depending on the type of asset, different modes of joint custody will be implemented, and the seller will be informed of the process upon acceptance of the product. ',
          'All expenses incurred in creating, maintaining, and managing the joint custody will be borne by the seller in addition to our charges, which will be billed accordingly.',
        ],
      },
      {
        title: 'Section 5: Insurance',
        listItems: [
          'The seller must arrange insurance for the asset equivalent to the tokenized value. ',
          'This insurance ensures coverage for the buyer in case of asset loss due to theft, damage, fire, earthquake, or similar events.',
        ],
      },
      {
        title: 'Section 6: Sale of Asset Tokens',
        listItems: [
          'Asset tokens will be available on the marketplace once the storage, security, and insurance processes for the physical asset are completed. ',
          ' All promotional activities for the sale of asset tokens will be managed by Rare Agora. ',
          'The seller may also conduct promotional activities through legitimate and legal means, in accordance with Amstar Metals – Rare Agora’s policies. ',
          'Rare Agora does not guarantee the sale of asset tokens, either partially or in full. Sales depend entirely on market demand and acceptance.',
        ],
      },
      {
        title: 'Section 7: Asset Value and Quantity',
        listItems: [
          'Before setting the asset value, the seller must consider factors such as market value, seller expectations, market acceptance, the physical condition of the <b>real-world asset (RWA)</b>, and other relevant factors. ',
          'Amstar Metals – Rare Agora can assist the seller in determining the asset value and quantity. ',
          'The final decision regarding the asset value and quantity rests with the seller.',
        ],
      },
      {
        title: 'Section 8: Project Cost',
        content: 'The project cost for the seller is divided into three parts: ',
        listItems: [
          `<b className="f-16-20-600-primary">Part 1</b>: The seller must pay for verification, authentication, and appraisal of the asset. The actual cost will be communicated upon product submission. `,
          `<b className="f-16-20-600-primary">Part 2</b>: The seller must pay upon approval of the asset by our expert team. This cost covers the tokenization process and minting of asset tokens. The actual cost will be communicated upon approval. `,
          `<b className="f-16-20-600-primary">Part 3</b>: The seller must pay before the asset tokens are made available online for sale. `,
        ],
        contentEnd:
          'Separate contracts will be sent to the seller for Part 1, and a second contract will cover Parts 2 and 3.',
      },
      {
        title: 'Section 9: General Conditions',
        listItems: [
          'The time taken for the sale of asset tokens on the online platform depends on market acceptance and demand. Rare Agora cannot commit to a specific timeline. ',
          'All payments made to Amstar Metals – Rare Agora are non-refundable under any circumstances. ',
          'If the project is delayed due to non-payment by the seller, Amstar Metals – Rare Agora will not be responsible for any direct or indirect losses incurred by the seller.',
        ],
      },
    ],
  },
};
