import { STATUS_TYPE } from '@helpers/constants/asset-status';

const API_METHODS = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
  PATCH: 'PATCH',
};

const END_POINTS = {
  socialSignin: '/auth/social-signin',
  signup: '/auth/signup',
  signin: '/auth/signin',
  confirmSignup: '/auth/confirm-signup',
  forgetPassword: '/auth/forgot-password',
  resetPassword: '/auth/confirm-forgot-password',
  logout: '/auth/logout',
  getFeatureAsset: '/api/assets/feature/asset',
  getExclusiveAccess: '/api/assets/exclusive-access',
  submitExclusiveAccess: '/api/assets/exclusive-access',
  getPriceHistory: (assetId: string) => `/api/assets/${assetId}/price/history`,
  confirmSocialSignin: (code: string) => `/auth/confirm-social-signin?code=${code}`,
  getAssetById: (assetId: string) => `/api/assets/${assetId}`,
  getAssetList: (page: number, limit: number) => `/api/assets/sold?page=${page}&size=${limit}`,
  getAssetByStatus: (
    status: STATUS_TYPE,
    search: string,
    category: string,
    page: number,
    limit: number,
    startDate: string,
    endDate: string,
    min: string,
    max: string,
    sortBy: string,
  ) =>
    `/api/assets/status/list?status=${status}&search=${search}&category=${category}&page=${page}&limit=${limit}&startDate=${startDate}&endDate=${endDate}&min=${min}&max=${max}&sortBy=${sortBy}`,
  getLiveAssetsList: '/api/assets/live/list',
  getCategoryList: '/api/assets/category/list',
  getBadgeCount: '/api/assets/submission/count',
  getUserDetail: '/api/user/detail',
  updateUser: '/api/user/update',
  createAsset: '/api/assets',
  assetsDraft: '/api/assets/draft',
  getAssetDraft: '/api/assets/draft',
  updateAsset: (assetId: string) => `/api/assets/${assetId}/update`,
  deleteAsset: (assetId: string) => `/api/assets/${assetId}/delete`,
  uploadDocuments: '/api/assets/create-documents',
  getCanceledOrder: (page: number, limit: number) => `/payments/orders?page=${page}&size=${limit}`,
  buyToken: '/payments/buy',
  createStripeAccount: '/users/create-stripe-account',
  getNotifications: `/api/assets/fetch-user/notification`,
  readAllNotifications: `/api/assets/notification/all-read`,
  readOneNotification: (id: string) => `/api/assets/notification/read/${id}`,
  assetPartialSearch: '/api/assets/partial-search',
  imageAnalysis: '/api/assets/analyze',
  getCollectionsCount: '/api/assets/collections/count',
  getCollectionsList: '/api/assets/collections/list',
  getFavourites: '/api/assets/wishlist',
  getFavouritesCount: (id: string) => `/api/assets/wishlist-count?assetId=${id}`,
  addfavourite: `/api/assets/wishlist`,
  getViewsCount: (id: string) => `/api/assets/views-count?assetId=${id}`,
  addViews: (id: string) => `/api/assets/views?assetId=${id}`,
  listAsset: `/api/assets/token/list`,
  deleteListings: (listingId: string) => `/api/assets/listings/${listingId}/delete`,
  userRewards: `/payments/user/rewards/list`,
  deleteDraft: (assetId: string) => `/api/assets/draft/${assetId}`,
  createApplicant: `/api/user/create/applicant`,
  getVerificationUrl: (applicantId: string) => `/api/user/verification/url/${applicantId}`,
  getApplicantDetails: (applicantId: string) => `/api/user/applicant/${applicantId}/details`,
  updateWalletAddress: `/api/user/wallet/address`,
  sendContactEmail: `/api/user/sendContactEmail`,
  verifyCryptoAddress: '/kyt/verify-crypto-address',
  verificationResult: '/kyt/verification-result',
  getStripeLoginLink: (accountId: string) => `/users/stripe/login/${accountId}`,
  aadhaarGenerateOtp: '/api/user/aadhaar/generate-otp',
  aadhaarVerifyOtp: '/api/user/aadhaar/verify-otp',
};

const ERROR_MESSAGE = {
  DEFAULT: 'Something went wrong',
  SESSION_EXPIRED: 'Kindly login to proceed.',
  WALLET_NOT_CONNECTED: 'Kindly connect your wallet',
};

export { API_METHODS, END_POINTS, ERROR_MESSAGE };
