export const tableData = {
  mockData: [
    {
      id: 'A001',
      assetId: 'A001',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Luxury Car',
      category: 'Vehicles',
      sellerName: 'John Doe',
      listedDate: '20-02-2024',
      totalViews: 1500,
      price: '$200,000',
      approvalStatus: 'Live',
      key: 1,
    },
    {
      id: 'A002',
      assetId: 'A002',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Gold Necklace',
      category: 'Jewelry',
      sellerName: 'Jessica Green',
      listedDate: '20-02-2023',
      totalViews: 1200,
      price: '$50,000',
      approvalStatus: 'Sold',
      key: 2,
    },
    {
      id: 'A003',
      assetId: 'A003',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Modern Sculpture',
      category: 'Art',
      sellerName: 'Alice Johnson',
      listedDate: '25-02-2030',
      totalViews: 800,
      price: '$75,000',
      approvalStatus: 'Sold',
      key: 3,
    },
    {
      id: 'A004',
      assetId: 'A004',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Vintage Watch',
      category: 'Watches',
      sellerName: 'David Brown',
      listedDate: '21-02-2024',
      totalViews: 1100,
      price: '$15,000',
      approvalStatus: 'Live',
      key: 4,
    },
    {
      id: 'A005',
      assetId: 'A005',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Antique Table',
      category: 'Furniture',
      sellerName: 'Sarah Lee',
      listedDate: '2025-02-05',
      totalViews: 900,
      price: '$20,000',
      approvalStatus: 'Delisted',
      key: 5,
    },
    {
      id: 'A006',
      assetId: 'A006',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Smartphone',
      category: 'Electronics',
      sellerName: 'Chris Brown',
      listedDate: '09-07-2006',
      totalViews: 1600,
      price: '$1,200',
      approvalStatus: 'Live',
      key: 6,
    },
    {
      id: 'A007',
      assetId: 'A007',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Designer Jacket',
      category: 'Fashion',
      sellerName: 'Linda White',
      listedDate: '09-02-2030',
      totalViews: 2000,
      price: '$2,500',
      approvalStatus: 'Sold',
      key: 7,
    },
    {
      id: 'A008',
      assetId: 'A008',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Electric Guitar',
      category: 'Music Instruments',
      sellerName: 'James Miller',
      listedDate: '20-05-2034',
      totalViews: 1400,
      price: '$3,000',
      approvalStatus: 'Sold',
      key: 8,
    },
    {
      id: 'A009',
      assetId: 'A009',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Mountain Bike',
      category: 'Sports',
      sellerName: 'Tom Harris',
      listedDate: '21-09-2034',
      totalViews: 700,
      price: '$500',
      approvalStatus: 'Delisted',
      key: 9,
    },
    {
      id: 'A010',
      assetId: 'A010',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Vintage Camera',
      category: 'Collectibles',
      sellerName: 'Emma Wilson',
      listedDate: '22-09-23',
      totalViews: 950,
      price: '$2,000',
      approvalStatus: 'Live',
      key: 10,
    },
  ],
  orders: [
    {
      id: 'A001',
      assetId: 'A001',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Luxury Car',
      category: 'Vehicles',
      sellerName: 'John Doe',
      listedDate: '20-02-2024',
      totalViews: 1500,
      price: '$200,000',
      approvalStatus: 'Live',
      key: 1,
      paymentMethod: 'stripe',
      refund: 'Received',
      paymentStatus: 'Successful',
    },
    {
      id: 'A002',
      assetId: 'A002',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Gold Necklace',
      category: 'Jewelry',
      sellerName: 'Jessica Green',
      listedDate: '20-02-2023',
      totalViews: 1200,
      price: '$50,000',
      approvalStatus: 'Sold',
      key: 2,
      paymentMethod: 'stripe',
      refund: 'Received',
      paymentStatus: 'Successful',
    },
    {
      id: 'A003',
      assetId: 'A003',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Modern Sculpture',
      category: 'Art',
      sellerName: 'Alice Johnson',
      listedDate: '25-02-2030',
      totalViews: 800,
      price: '$75,000',
      approvalStatus: 'Sold',
      key: 3,
      paymentMethod: 'wallet',
      refund: 'Pending',
      paymentStatus: 'Successful',
    },
    {
      id: 'A004',
      assetId: 'A004',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Vintage Watch',
      category: 'Watches',
      sellerName: 'David Brown',
      listedDate: '21-02-2024',
      totalViews: 1100,
      price: '$15,000',
      approvalStatus: 'Live',
      key: 4,
      paymentMethod: 'wallet',
      refund: 'Pending',
      paymentStatus: 'Pending',
    },
    {
      id: 'A005',
      assetId: 'A005',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Antique Table',
      category: 'Furniture',
      sellerName: 'Sarah Lee',
      listedDate: '2025-02-05',
      totalViews: 900,
      price: '$20,000',
      approvalStatus: 'Delisted',
      key: 5,
      paymentMethod: 'wallet',
      refund: 'Failed',
      paymentStatus: 'Pending',
    },
    {
      id: 'A006',
      assetId: 'A006',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Smartphone',
      category: 'Electronics',
      sellerName: 'Chris Brown',
      listedDate: '09-07-2006',
      totalViews: 1600,
      price: '$1,200',
      approvalStatus: 'Live',
      key: 6,
      paymentMethod: 'stripe',
      refund: 'Pending',
      paymentStatus: 'Pending',
    },
    {
      id: 'A007',
      assetId: 'A007',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Designer Jacket',
      category: 'Fashion',
      sellerName: 'Linda White',
      listedDate: '09-02-2030',
      totalViews: 2000,
      price: '$2,500',
      approvalStatus: 'Sold',
      key: 7,
      paymentMethod: 'wallet',
      refund: 'Received',
      paymentStatus: 'Failed',
    },
    {
      id: 'A008',
      assetId: 'A008',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Electric Guitar',
      category: 'Music Instruments',
      sellerName: 'James Miller',
      listedDate: '20-05-2034',
      totalViews: 1400,
      price: '$3,000',
      approvalStatus: 'Sold',
      key: 8,
      paymentMethod: 'stripe',
      refund: 'Received',
      paymentStatus: 'Failed',
    },
    {
      id: 'A009',
      assetId: 'A009',
      coverImage: '/assets/CarloDolci.jpg',
      assetName: 'Mountain Bike',
      category: 'Sports',
      sellerName: 'Tom Harris',
      listedDate: '21-09-2034',
      totalViews: 700,
      price: '$500',
      approvalStatus: 'Delisted',
      key: 9,
      paymentMethod: 'stripe',
      refund: 'Pending',
      paymentStatus: 'Failed',
    },
  ],
};
export interface ApprovedAssetsInterface {
  id: string;
  assetId: string;
  assetImageUrl: string;
  assetName: string;
  category: string;
  sellerName: string;
  listedDate: string;
  totalViews: number;
  price: string;
  approvalStatus: ApprovalStatus;
}

export type ApprovalStatus = 'Live' | 'Sold' | 'Deleted' | 'Delisted';

export const footerContent = {
  logo: '../../public/Rare_Agora_LOGO.png', // Path to your logo
  tagline: 'Own a piece of iconic assets—art, property, luxury items, all in one intuitive blockchain platform.',
  socialMedia: [
    { icon: 'twitter', url: 'https://twitter.com' },
    { icon: 'linkedin', url: 'https://linkedin.com' },
  ],
  copyright: '© Copyright 2025 RWA – All Rights Reserved.',
  links: [
    { text: 'Terms of Service', url: '/policy?target=tos' },
    { text: 'Privacy Policy', url: '/policy?target=privacy' },
  ],
  resources: [
    { text: 'Blogs', url: '/blogs' },
    { text: 'Reward Points', url: '/rewards' },
    { text: 'FAQs', url: '/faq' },
  ],
  legal: [
    { text: 'Buyer Terms', url: '/terms?target=buyer' },
    { text: 'Seller Terms', url: '/terms?target=seller' },
  ],
  Company: [
    { text: 'About Us', url: '/aboutUs' },
    { text: 'Contact Us', url: '/contactUs' },
  ],
};
